create table if not exists ldap_sync_users
(
  id                int unsigned auto_increment
    primary key,
  name              varchar(255) not null,
  ldap_connection_src             varchar(255) not null,
  ldap_base_dn_src                  varchar(255) not null,
  ldap_filter_src                    varchar(255) not null,
  syncjob_reference_id             INTEGER,
  email             varchar(255) null,
  email_verified_at timestamp    null,
  password          varchar(255) null,
  remember_token    varchar(100) null,
  created_at        timestamp    null,
  updated_at        timestamp    null,
  department             varchar(255) null,
  departmentNumber             varchar(255) null,
  title             varchar(255) null,
  firstName             varchar(255) null,
  lastName             varchar(255) null,
  info             varchar(255) null,
  initials             varchar(255) null,
  country             varchar(255) null,
  streetAddress             varchar(255) null,
  postalCode             varchar(255) null,
  postOfficeBox             varchar(255) null,
  physicalDeliveryOfficeName             varchar(255) null,
  telephone             varchar(255) null,
  facsimile             varchar(255) null,
  locale             varchar(255) null,
  company             varchar(255) null,
  homeMdb             varchar(255) null,
  homeDrive             varchar(255) null,
  homeDirectory             varchar(255) null,
  emailNickname             varchar(255) null,
  userPrincipalName             varchar(255) null,
  scriptPath             varchar(255) null,
  badPasswordCount             integer null,
  badPasswordTime             timestamp null,
  passwordLastSet             varchar(255) null,
  lockoutTime             varchar(255) null,
  profilePath             varchar(255) null,
  legacyExchangeDn             varchar(255) null,
  accountExpires             timestamp null,
  thumbnail             varchar(255) null,
  jpegPhoto             varchar(255) null,
  manager             varchar(255) null,
  employee             integer null,
  employeeType             varchar(255) null,
  employeeNumber             integer null,
  roomNumber             varchar(255) null,
  personalTitle             varchar(255) null,
  constraint users_email_unique
    unique (email)
)
  collate = utf8mb4_unicode_ci;
